- Math/CountingBits.swift
- README.md
> add solution for 338. Counting Bits

- DFS/CourseSchedule.swift
- DFS/CourseScheduleII.swift
Please have a look at my accepted solution, thank you
> [DFS] Add a solution to Course Schedule & Course Schedule II

- README.md
- Tree/RecoverBinarySearchTree.swift
Please have a look at my accepted solution for 99. Recover Binary Search Tree
> [Tree] Add a solution to Recover Binary Search Tree

- DP/GuessNumberHigherOrLowerII.swift
- README.md
Please have a look at my accepted solution for 375. Guess Number Higher or Lower II
> [DP]Add a solution to Guess Number Higher or Lower II

- Tree/UniqueBinarySearchTrees.swift
2 loop? Or did I miss something?
> O(n) -> O(n^2)

- README.md
- Sort/ArrayPartitionI.swift
- Tree/MergeTwoBinaryTrees.swift
The solution of the [Merge Two Binary Trees](https://leetcode.com/problems/merge-two-binary-trees/description/).
Signed-off-by: Desgard_Duan <gua@desgard.com>
> Add solution for Merge Two Binary Trees

- Array/ProductExceptSelf.swift
Fixes compile errors on LeetCode site.
> Update syntax for Swift 4

- Math/ReverseInteger.swift
"Note:
Assume we are dealing with an environment which could only hold integers within the 32-bit signed integer range. For the purpose of this problem, assume that your function returns 0 when the reversed integer overflows."
if x input 1563847412 , res will become overflows.
> Fix Reverse Integer

- README.md
- Tree/ValidateBinarySearchTree.swift
The big O for space should be O(log n) given the most it takes will be for the depth of the tree for those recursive calls on the stack.
> O(n) -> O(log n) for validate BST space big O

- String/ValidPalindromeII.swift
You can reduce the two similar while loops into a single one if you use a boolean to determine when you should stop.
> Simplify ValidPalindromeII.swift

- Array/ProductExceptSelf.swift
Both speed and space beat 100% other Swift version online
> Update #ProductExceptSelf with a faster speed than 100% Swift online

- DP/LongestPalindromicSubstring.swift
- cast strings directly to an array of Chars
- count property of String type is available
> Update LongestPalindromicSubstring For Swift 5

- Array/ProductExceptSelf.swift
Because of The problem statement mentions that  don't using divide,but the solution  use divide in last line in file,  the advantages of the solution is use less space  .  So  I add back   solution    that do not using divide as before. The time cost is almost same both solution.
>  238. Product of Array Except Self  need add  solution  that as before

- Array/FindDisappearedNumbers.swift
- README.md
Hi. I add solution for [#448](https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/) question in LeetCode.
> [Array] Add a solution to Find All Numbers Disappeared in an Array

- Queue/ImplementQueueUsingStacks.swift
- README.md
Hello everyone. I add solution for #232 question in LeetCode.
https://leetcode.com/problems/implement-queue-using-stacks/
> #232 Queue question solution

- README.md
- Stack/BasicCalculator.swift
[Stack] Add a solution to Basic Calculator
> [Stack] Add a solution to Basic Calculator

- Array/MinimumSizeSubarraySum.swift
Just two minor fixes. 
1. It should be valid instead of invalid. 
2. It's recommended to use ',' instead of "&&" IMO.
> [Array] Fix typo, should be valid instead of invalid

- README.md
As the title says, the file link is pointing incorrect file.
> [README] Fix readme file link to 'Search Insert Position'

- README.md
Rename Bnary to Binary and fix link to solution
> Fix Binary Tree Paths titles and links

- String/MultiplyStrings.swift
- Used wholeNumberValue to convert char to int
- Removed unnecessary isEmpty check on "trim starting 0"
> updated solution for multiplyStrings
